name: Run Codeception test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run:  composer install

#      - name: Run chromedriver
#        run:  nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &

      - name: Run test cases
        run:  php vendor/bin/codecept run unit

#      - name: Run test cases
#        run:  php vendor/bin/codecept run unit --steps